# Generated by Django 4.0.4 on 2022-07-05 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista_presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=50, verbose_name='Condição')),
                ('data_criacao', models.CharField(max_length=50)),
                ('turma', models.CharField(max_length=5)),
                ('codigo', models.CharField(default='0', max_length=6, verbose_name='Código')),
                ('condicao', models.CharField(default='0', max_length=1, verbose_name='Condição')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=15, verbose_name='Matrícula')),
                ('identificador_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.lista_presenca')),
            ],
        ),
    ]
